-- AlterTable
ALTER TABLE "public"."Empresa"
ADD COLUMN "faviconUrl" TEXT,
ADD COLUMN "creci" TEXT,
ADD COLUMN "slogan" TEXT,
ADD COLUMN "corPrimaria" TEXT DEFAULT '#0B1F3A',
ADD COLUMN "corSecundaria" TEXT DEFAULT '#C9A227',
ADD COLUMN "numero" TEXT,
ADD COLUMN "complemento" TEXT,
ADD COLUMN "bairro" TEXT,
ADD COLUMN "instagram" TEXT,
ADD COLUMN "facebook" TEXT,
ADD COLUMN "linkedin" TEXT,
ADD COLUMN "youtube" TEXT,
ADD COLUMN "horarioAtendimento" TEXT,
ADD COLUMN "googleMapsUrl" TEXT,
ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "siteTitulo" TEXT,
ADD COLUMN "siteDescricao" TEXT,
ADD COLUMN "seoKeywords" TEXT,
ADD COLUMN "siteAtivo" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "siteExibirCorretores" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "siteExibirBlog" BOOLEAN NOT NULL DEFAULT true;
